# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/iceman/Developer/Projects/emscripten

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/iceman/Developer/Projects/emscripten

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iceman/Developer/Projects/emscripten/CMakeFiles /home/iceman/Developer/Projects/emscripten//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iceman/Developer/Projects/emscripten/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named syntax_highlight

# Build rule for target.
syntax_highlight: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 syntax_highlight
.PHONY : syntax_highlight

# fast build rule for target.
syntax_highlight/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_highlight.dir/build.make CMakeFiles/syntax_highlight.dir/build
.PHONY : syntax_highlight/fast

#=============================================================================
# Target rules for targets named cpp_lib

# Build rule for target.
cpp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_lib
.PHONY : cpp_lib

# fast build rule for target.
cpp_lib/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/cpp_lib.dir/build.make lib/CMakeFiles/cpp_lib.dir/build
.PHONY : cpp_lib/fast

syntax_highlight.o: syntax_highlight.c.o
.PHONY : syntax_highlight.o

# target to build an object file
syntax_highlight.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_highlight.dir/build.make CMakeFiles/syntax_highlight.dir/syntax_highlight.c.o
.PHONY : syntax_highlight.c.o

syntax_highlight.i: syntax_highlight.c.i
.PHONY : syntax_highlight.i

# target to preprocess a source file
syntax_highlight.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_highlight.dir/build.make CMakeFiles/syntax_highlight.dir/syntax_highlight.c.i
.PHONY : syntax_highlight.c.i

syntax_highlight.s: syntax_highlight.c.s
.PHONY : syntax_highlight.s

# target to generate assembly for a file
syntax_highlight.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/syntax_highlight.dir/build.make CMakeFiles/syntax_highlight.dir/syntax_highlight.c.s
.PHONY : syntax_highlight.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cpp_lib"
	@echo "... syntax_highlight"
	@echo "... syntax_highlight.o"
	@echo "... syntax_highlight.i"
	@echo "... syntax_highlight.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

